from setuptools import setup, find_packages

setup(
    name="eegspeech",
    version="2.0.0",
    description="Advanced healthcare BCI with VLM integration for clinical EEG analysis and speech decoding",
    long_description=open("README.md").read() if open("README.md", errors="ignore") else "",
    long_description_content_type="text/markdown",
    author="Your Name",
    author_email="your.email@example.com",
    url="https://github.com/yourusername/eegspeech",
    license="MIT",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.26.0,<2.0.0",
        "torch>=2.2.0,<3.0.0",
        "matplotlib>=3.10.0,<4.0.0",
        "scikit-learn>=1.6.0,<2.0.0",
        "streamlit>=1.44.0,<2.0.0",
        "plotly>=6.0.0,<7.0.0",
        "scipy>=1.15.0,<2.0.0",
        "mne>=1.8.0,<2.0.0",
        "seaborn>=0.13.0,<0.14.0",
        "torchinfo>=1.8.0,<2.0.0",
        "pandas>=2.2.0,<3.0.0",
        "pillow>=11.0.0,<12.0.0",
        "altair>=5.5.0,<6.0.0",
        "pyarrow>=20.0.0,<21.0.0",
        "pydeck>=0.9.0,<0.10.0",
        "requests>=2.32.0,<3.0.0",
        "jinja2>=3.1.0,<4.0.0",
        "transformers>=4.36.0,<5.0.0",
        "opencv-python>=4.8.0,<5.0.0",
        "openai>=1.0.0,<2.0.0",
        "accelerate>=0.25.0,<1.0.0",
        "timm>=0.9.0,<1.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.0.0,<9.0.0",
            "black>=24.0.0,<25.0.0",
            "flake8>=7.0.0,<8.0.0",
        ],
        "vlm": [
            "transformers>=4.36.0,<5.0.0",
            "opencv-python>=4.8.0,<5.0.0",
            "openai>=1.0.0,<2.0.0",
            "accelerate>=0.25.0,<1.0.0",
            "timm>=0.9.0,<1.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "eegspeech=eegspeech.app.cli:main",
            "eegspeech-healthcare=eegspeech.app.healthcare_cli:main",
        ],
    },
    python_requires=">=3.8,<3.12",
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
    ],
)